ecmaFeatures:
  modules: true
  jsx: true
  generators: false
  objectLiteralDuplicateProperties: false

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

env:
  amd: false
  browser: true
  es6: true
  jquery: false
  node: true
  mocha: false
  jasmine: true

rules:
  # Possible Errors
  comma-dangle:
    - error
    - always-multiline
  no-cond-assign:
    - error
    - always
  no-console: warn
  no-constant-condition: warn
  no-control-regex: error
  no-debugger: warn
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens:
    - error
    - functions
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-negated-in-lhs: error
  no-obj-calls: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-unexpected-multiline: off
  no-unreachable: error
  use-isnan: error
  valid-jsdoc: error
  valid-typeof: error

  # Best Practices
  accessor-pairs: off
  array-callback-return: error
  block-scoped-var: error
  complexity: warn
  consistent-return: error
  curly:
    - error
    - multi-line
  default-case: error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: true
  eqeqeq: error
  guard-for-in: error
  id-blacklist: off
  no-alert: warn
  no-caller: error
  no-case-declarations: error
  no-div-regex: off
  no-else-return: error
  no-extra-label: error
  no-empty-pattern: error
  no-eq-null: off
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-fallthrough: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: warn
  no-multi-spaces: error
  no-multi-str: error
  no-native-reassign: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign:
    - error
    - props: false
  no-process-env: off
  no-proto: error
  no-redeclare: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: off
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-void: off
  no-warning-comments:
    - warn
    - terms:
        - todo
        - fixme
      location: start
  no-with: error
  radix: error
  vars-on-top: error
  wrap-iife:
    - error
    - outside
  yoda: error

  # Strict
  strict: error

  # Variables
  init-declarations: off
  no-catch-shadow: off
  no-delete-var: error
  no-implicit-globals: off
  no-label-var: off
  no-self-assign: error
  no-shadow-restricted-names: error
  no-shadow: error
  no-undef-init: off
  no-undef: error
  no-undefined: off
  no-unused-vars:
    - error
    - args: after-used
  no-use-before-define: error

  # Node.js and CommonJS
  callback-return: off
  global-require: off
  handle-callback-err: off
  no-mixed-requires: off
  no-new-require: error
  no-path-concat: error
  no-process-exit: off
  no-restricted-modules: off
  no-sync: off

  # Stylistic Issues
  array-bracket-spacing:
    - error
    - never
  block-spacing: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
    - properties: always
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  consistent-this: off
  eol-last: error
  func-names: off
  func-style: off
  id-length: off
  id-match: off
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: 1
  jsx-quotes:
    - error
    - prefer-double
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  keyword-spacing:
    - error
    - before: true
      after: true
      overrides:
        return:
          after: true
        throw:
          after: true
        case:
          after: true
  linebreak-style: off
  lines-around-comment: off
  max-depth:
    - warn
    - 4
  max-len:
    - warn
    - 100
    - 2
    - ignoreUrls: true
      ignoreComments: false
  max-nested-callbacks:
    - warn
    - max: 5
  max-params:
    - warn
    - max: 5
  max-statements: off
  new-cap:
    - error
    - newIsCap: true
  new-parens: error
  newline-after-var: off
  newline-before-return: off
  newline-per-chained-call: off
  no-array-constructor: error
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-spaces-and-tabs: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  no-negated-condition: off
  no-nested-ternary: error
  no-new-object: error
  no-plusplus: off
  no-spaced-func: error
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: off
  no-unneeded-ternary:
    - error
    - defaultAssignment: false
  no-whitespace-before-property: error
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - var: never
      let: never
      const: never
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment: off
  operator-linebreak: off
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
    - keywords: false
      unnecessary: true
      numbers: false
  quotes:
    - error
    - single
    - avoid-escape
  require-jsdoc:
    - warn
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  semi-spacing:
    - error
    - before: false
      after: true
  semi:
    - error
    - always
  sort-vars: off
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: off
  spaced-comment:
    - error
    - always
    - exceptions:
        - '-'
        - '+'
  wrap-regex: off

  # ECMAScript 6
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - before: true
      after: true
  constructor-super: error
  generator-star-spacing: off
  no-class-assign: off
  no-confusing-arrow: off
  no-const-assign: error
  no-new-symbol: error
  no-restricted-globals: off
  no-restricted-imports: off
  no-dupe-class-members: error
  no-this-before-super: error
  no-var: error
  no-useless-constructor: error
  object-shorthand:
    - error
    - always
  prefer-arrow-callback: error
  prefer-const: error
  prefer-spread: off
  prefer-reflect: off
  prefer-rest-params: error
  prefer-template: error
  require-yield: off
  sort-imports: off
  template-curly-spacing: error
  yield-star-spacing:
    - error
    - after

  # React
  react/display-name: error
  react/jsx-no-duplicate-props: error
  react/jsx-no-undef: error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/no-deprecated: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-is-mounted: error
  react/no-unknown-property: error
  react/no-render-return-value: error
  react/prop-types: error
  react/react-in-jsx-scope: error
  react/require-render-return: error
